### ISSUE TITLE
x86 fpylog tests cannot be executed on x64 Linux

### ISSUE THREAD

**Issue by kr0st** [kr0st/fplog#76]
```
[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from Fpylog_Test
[ RUN      ] Fpylog_Test.All_Tests
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/fplog/build_architecture/x86_32/build_target_os/Linux/Stage/fplog_wrapper.py", line 13, in <module>
    lib = imp.load_dynamic('fpylog', os.path.join(cur_path, 'libfpylog3.dylib'))
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /var/lib/jenkins/workspace/fplog/build_architecture/x86_32/build_target_os/Linux/Stage/libfpylog3.dylib: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fpylog_test.py", line 6, in <module>
    import fplog_wrapper as fpylog
  File "/var/lib/jenkins/workspace/fplog/build_architecture/x86_32/build_target_os/Linux/Stage/fplog_wrapper.py", line 15, in <module>
    lib = imp.load_dynamic('fpylog', os.path.join(cur_path, 'libfpylog.so'))
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /var/lib/jenkins/workspace/fplog/build_architecture/x86_32/build_target_os/Linux/Stage/libfpylog.so: wrong ELF class: ELFCLASS32
unknown file: Failure
Unknown C++ exception thrown in the test body.
```

**Comment by kr0st** [comment]
For now fpylog tests removed from 32-bit builds. fpylog 32bit is not supported at all for now - feature is not important enough to spend a lot of time on making it 32-bit friendly.
